"""
Export well data to LAS file format.
"""

from __future__ import annotations

import io
import lasio
import pandas as pd
from datetime import datetime


def export_well_to_las(well: dict) -> bytes:
    """Export well data to LAS format.
    
    Parameters
    ----------
    well : dict
        Well data dictionary with keys: name, df, depth, info, units
    
    Returns
    -------
    bytes
        LAS file content as bytes
    """
    try:
        # Create LAS file
        las = lasio.LASFile()
        
        # Set well header information
        well_info = well.get("info", {})
        las.well["WELL"] = lasio.HeaderItem("WELL", value=well.get("name", "UNKNOWN"))
        las.well["FIELD"] = lasio.HeaderItem("FIELD", value=well_info.get("field", ""))
        las.well["COMP"] = lasio.HeaderItem("COMP", value=well_info.get("company", ""))
        las.well["KB"] = lasio.HeaderItem("KB", value=well_info.get("kb", 0.0))
        las.well["STRT"] = lasio.HeaderItem("STRT", value=well_info.get("strt", 0.0))
        las.well["STOP"] = lasio.HeaderItem("STOP", value=well_info.get("stop", 0.0))
        las.well["STEP"] = lasio.HeaderItem("STEP", value=well_info.get("step", 0.5))
        
        # Set other header information
        las.other = f"Generated by Multi-Well Viewer\nMerged well: {well.get('wells_merged', ('Unknown', 'Unknown'))}\nGenerated: {datetime.now().isoformat()}"
        
        # Get dataframe
        df = well["df"].copy()
        depth_col = df.columns[0]
        
        # Rename depth column to DEPTH if needed
        if depth_col != "DEPTH":
            df = df.rename(columns={depth_col: "DEPTH"})
        
        # Process each curve column
        for col in df.columns:
            if col == "DEPTH":
                continue
            
            # For merged wells with NaN values, use interpolation and forward/backward fill
            # This maintains data continuity for merged well logs
            values = df[col].copy()
            
            # Use pandas Series for better handling
            series = pd.Series(values)
            
            # First interpolate linearly to fill small gaps
            series = series.interpolate(method='linear', limit_direction='both')
            
            # Then forward and backward fill remaining NaN values
            series = series.fillna(method='ffill').fillna(method='bfill')
            
            # For any remaining NaN at edges, fill with 0 or the nearest value
            series = series.fillna(0)
            
            values = series.values
            
            unit = well.get("units", {}).get(col, "")
            
            # Create curve
            curve = lasio.CurveItem(
                mnemonic=col,
                unit=unit,
                value="",
                description=col
            )
            las.append_curve(curve, values)
        
        # Set depth column
        las.set_data(df[["DEPTH"] + [c for c in df.columns if c != "DEPTH"]].values)
        
        # Write to bytes buffer
        buffer = io.BytesIO()
        las.write(buffer, version=2.0)
        buffer.seek(0)
        
        return buffer.getvalue()
    
    except Exception as e:
        print(f"Error exporting to LAS: {e}")
        return b""


def export_well_to_csv(well: dict) -> bytes:
    """Export well data to CSV format (alternative).
    
    Parameters
    ----------
    well : dict
        Well data dictionary
    
    Returns
    -------
    bytes
        CSV file content as bytes
    """
    try:
        df = well["df"].copy()
        buffer = io.StringIO()
        df.to_csv(buffer, index=False)
        return buffer.getvalue().encode('utf-8')
    
    except Exception as e:
        print(f"Error exporting to CSV: {e}")
        return b""
